services:
  - type: web
    name: real-estate-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://real_estate_user:6ImpADxTrdHtuNwnX9L6TF5Yx208WwK2@dpg-d246p1p5pdvs73fvn1h0-a.singapore-postgres.render.com/real_estate_db_qygu
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app