services:
  - type: web
    name: real-estate-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString

databases:
  - name: real-estate-db
    plan: free
    type: postgres
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all