services:
  - type: web
    name: real-estate-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
      - key: MYSQL_HOST
        fromDatabase:
          name: real-estate-db
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: real-estate-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: real-estate-db
          property: password
      - key: MYSQL_DB
        fromDatabase:
          name: real-estate-db
          property: database

databases:
  - name: real-estate-db
    databaseName: real_estate_db
    user: real_estate_user
    plan: free 